# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
t1 = Teacher.create(name:"Mr. Jones")

p1 = Period.create(subject:"Physics", teacher_id:t1.id)
p2 = Period.create(subject:"Biology", teacher_id:t1.id)
p3 = Period.create(subject:"Biology", teacher_id:t1.id)
p5 = Period.create(subject:"Robotics Engineering", teacher_id:t1.id)
p6 = Period.create(subject:"Freshmen Science 2", teacher_id:t1.id)

s1 = Student.create(name:'Steve Rodgers', preferred_name: 'Michael', preferred_pronoun:'He/Him')
s2 = Student.create(name:'Jane Doe', preferred_name: 'J', preferred_pronoun:'He/Him')
s3 = Student.create(name:'Al Student', preferred_name: 'Alberto', preferred_pronoun:'They/Them')
s4 = Student.create(name:'Al Roker', preferred_name: 'Albert', preferred_pronoun:'He/Him')
s5 = Student.create(name:'Maggie James', preferred_name: 'Mags', preferred_pronoun:'She/Her')
s6 = Student.create(name:'Bob Jones', preferred_name: 'Robert', preferred_pronoun:'They/Them')
s7 = Student.create(name:'Steve Peters', preferred_name: 'Steven', preferred_pronoun:'He/Him')
s8 = Student.create(name:'Otto Octavious', preferred_name: 'Doc', preferred_pronoun:'He/Him')
s9 = Student.create(name:'Peter Parker', preferred_name: 'Pete', preferred_pronoun:'He/Him')
s10 = Student.create(name:'MJ Watson', preferred_name: 'MJ', preferred_pronoun:'She/Her')
s11 = Student.create(name:'Frank Castle', preferred_name: 'Michael', preferred_pronoun:'She/Her')
s12 = Student.create(name:'Miles Morales', preferred_name: 'J', preferred_pronoun:'He/Him')
s13 = Student.create(name:'Flash Thompson', preferred_name: 'Alberto', preferred_pronoun:'They/Them')
s14 = Student.create(name:'Curt Conners', preferred_name: 'Albert', preferred_pronoun:'He/Him')
s15 = Student.create(name:'Harry Osborn', preferred_name: 'Mags', preferred_pronoun:'She/Her')
s16 = Student.create(name:'Jonah Jameison', preferred_name: 'Robert', preferred_pronoun:'They/Them')
s17 = Student.create(name:'Frodo', preferred_name: 'Steven', preferred_pronoun:'He/Him')
s18 = Student.create(name:'Harry Potter', preferred_name: 'Doc', preferred_pronoun:'He/Him')
s19 = Student.create(name:'Tony Stank', preferred_name: 'Pete', preferred_pronoun:'He/Him')
s20 = Student.create(name:'Stan Lee', preferred_name: 'MJ', preferred_pronoun:'She/Her')
s21 = Student.create(name:'Bruce Banner', preferred_name: 'Michael', preferred_pronoun:'She/Her')
s22 = Student.create(name:'Hank Pym', preferred_name: 'J', preferred_pronoun:'He/Him')
s23 = Student.create(name:'Clint Barton', preferred_name: 'Alberto', preferred_pronoun:'They/Them')
s24 = Student.create(name:'Scott Summers', preferred_name: 'Albert', preferred_pronoun:'He/Him')
s25 = Student.create(name:'Jean Grey', preferred_name: 'Mags', preferred_pronoun:'She/Her')
s26 = Student.create(name:'Hank Mccoy', preferred_name: 'Robert', preferred_pronoun:'They/Them')
s27 = Student.create(name:'Bobby Drake', preferred_name: 'Steven', preferred_pronoun:'He/Him')
s28 = Student.create(name:'Billy Idol', preferred_name: 'Doc', preferred_pronoun:'He/Him')
s29 = Student.create(name:'Ganke Lee', preferred_name: 'Pete', preferred_pronoun:'He/Him')
s30 = Student.create(name:'Jessica Jones', preferred_name: 'MJ', preferred_pronoun:'She/Her')

Registration.create(teacher_id:t1.id, student_id:s1.id)
Registration.create(teacher_id:t1.id, student_id:s2.id)
Registration.create(teacher_id:t1.id, student_id:s3.id)
Registration.create(teacher_id:t1.id, student_id:s4.id)
Registration.create(teacher_id:t1.id, student_id:s5.id)
Registration.create(teacher_id:t1.id, student_id:s6.id)
Registration.create(teacher_id:t1.id, student_id:s7.id)
Registration.create(teacher_id:t1.id, student_id:s8.id)
Registration.create(teacher_id:t1.id, student_id:s9.id)
Registration.create(teacher_id:t1.id, student_id:s10.id)

StudentsPeriod.create(period_id:p1.id, student_id:s10.id)
StudentsPeriod.create(period_id:p1.id, student_id:s9.id)
StudentsPeriod.create(period_id:p1.id, student_id:s8.id)
StudentsPeriod.create(period_id:p1.id, student_id:s7.id)
StudentsPeriod.create(period_id:p1.id, student_id:s6.id)
StudentsPeriod.create(period_id:p2.id, student_id:s15.id)
StudentsPeriod.create(period_id:p2.id, student_id:s29.id)
StudentsPeriod.create(period_id:p2.id, student_id:s17.id)
StudentsPeriod.create(period_id:p2.id, student_id:s28.id)
StudentsPeriod.create(period_id:p2.id, student_id:s3.id)
StudentsPeriod.create(period_id:p2.id, student_id:s9.id)
StudentsPeriod.create(period_id:p2.id, student_id:s6.id)
StudentsPeriod.create(period_id:p1.id, student_id:s3.id)
StudentsPeriod.create(period_id:p1.id, student_id:s2.id)
StudentsPeriod.create(period_id:p1.id, student_id:s13.id)
StudentsPeriod.create(period_id:p1.id, student_id:s26.id)
StudentsPeriod.create(period_id:p1.id, student_id:s16.id)
StudentsPeriod.create(period_id:p2.id, student_id:s5.id)
StudentsPeriod.create(period_id:p2.id, student_id:s1.id)
StudentsPeriod.create(period_id:p2.id, student_id:s4.id)
StudentsPeriod.create(period_id:p2.id, student_id:s27.id)
StudentsPeriod.create(period_id:p2.id, student_id:s18.id)
StudentsPeriod.create(period_id:p2.id, student_id:s19.id)
StudentsPeriod.create(period_id:p2.id, student_id:s20.id)


Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s1.id,cycle:1)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s1.id,cycle:2)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s1.id,cycle:3)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s1.id,cycle:4)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s1.id,cycle:5)

Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s2.id,cycle:1)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s2.id,cycle:2)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s2.id,cycle:3)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s2.id,cycle:4)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s2.id,cycle:5)

Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s3.id,cycle:1)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s3.id,cycle:2)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s3.id,cycle:3)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s3.id,cycle:4)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s3.id,cycle:5)

Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s4.id,cycle:1)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s4.id,cycle:2)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s4.id,cycle:3)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s4.id,cycle:4)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s4.id,cycle:5)

Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s5.id,cycle:1)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s5.id,cycle:2)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s5.id,cycle:3)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s5.id,cycle:4)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s5.id,cycle:5)

Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s6.id,cycle:1)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s6.id,cycle:2)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s6.id,cycle:3)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s6.id,cycle:4)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s6.id,cycle:5)

Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s7.id,cycle:1)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s7.id,cycle:2)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s7.id,cycle:3)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s7.id,cycle:4)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s7.id,cycle:5)

Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s8.id,cycle:1)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s8.id,cycle:2)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s8.id,cycle:3)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s8.id,cycle:4)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s8.id,cycle:5)

Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s9.id,cycle:1)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s9.id,cycle:2)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s9.id,cycle:3)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s9.id,cycle:4)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s9.id,cycle:5)

Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s10.id,cycle:1)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s10.id,cycle:2)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s10.id,cycle:3)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s10.id,cycle:4)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s10.id,cycle:5)