# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
t1 = Teacher.create(name:"Mr. Jones")

p1 = Period.create(subject:"Physics", teacher_id:t1.id)
p2 = Period.create(subject:"Biology", teacher_id:t1.id)

s1 = Student.create(name:'Mike Jones', preferred_name: 'Michael', preferred_pronoun:'She/Her')
s2 = Student.create(name:'Jane Doe', preferred_name: 'J', preferred_pronoun:'He/Him')
s3 = Student.create(name:'Al Student', preferred_name: 'Alberto', preferred_pronoun:'They/Them')
s4 = Student.create(name:'Al Roker', preferred_name: 'Albert', preferred_pronoun:'He/Him')
s5 = Student.create(name:'Maggie James', preferred_name: 'Mags', preferred_pronoun:'She/Her')
s6 = Student.create(name:'Bob Jones', preferred_name: 'Robert', preferred_pronoun:'They/Them')
s7 = Student.create(name:'Steve Peters', preferred_name: 'Steven', preferred_pronoun:'He/Him')
s8 = Student.create(name:'Otto Octavious', preferred_name: 'Doc', preferred_pronoun:'He/Him')
s9 = Student.create(name:'Peter Parker', preferred_name: 'Pete', preferred_pronoun:'He/Him')
s10 = Student.create(name:'MJ Watson', preferred_name: 'MJ', preferred_pronoun:'She/Her')

Registration.create(teacher_id:t1.id, student_id:s1.id)
Registration.create(teacher_id:t1.id, student_id:s2.id)
Registration.create(teacher_id:t1.id, student_id:s3.id)
Registration.create(teacher_id:t1.id, student_id:s4.id)
Registration.create(teacher_id:t1.id, student_id:s5.id)
Registration.create(teacher_id:t1.id, student_id:s6.id)
Registration.create(teacher_id:t1.id, student_id:s7.id)
Registration.create(teacher_id:t1.id, student_id:s8.id)
Registration.create(teacher_id:t1.id, student_id:s9.id)
Registration.create(teacher_id:t1.id, student_id:s10.id)

StudentsPeriod.create(period_id:p1.id, student_id:s1.id)
StudentsPeriod.create(period_id:p1.id, student_id:s2.id)
StudentsPeriod.create(period_id:p1.id, student_id:s3.id)
StudentsPeriod.create(period_id:p1.id, student_id:s4.id)
StudentsPeriod.create(period_id:p1.id, student_id:s5.id)
StudentsPeriod.create(period_id:p2.id, student_id:s6.id)
StudentsPeriod.create(period_id:p2.id, student_id:s7.id)
StudentsPeriod.create(period_id:p2.id, student_id:s8.id)
StudentsPeriod.create(period_id:p2.id, student_id:s9.id)
StudentsPeriod.create(period_id:p2.id, student_id:s10.id)
StudentsPeriod.create(period_id:p2.id, student_id:s5.id)
StudentsPeriod.create(period_id:p2.id, student_id:s4.id)

Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s1.id,cycle:1)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s1.id,cycle:2)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s1.id,cycle:3)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s1.id,cycle:4)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s1.id,cycle:5)

Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s2.id,cycle:1)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s2.id,cycle:2)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s2.id,cycle:3)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s2.id,cycle:4)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s2.id,cycle:5)

Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s3.id,cycle:1)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s3.id,cycle:2)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s3.id,cycle:3)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s3.id,cycle:4)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s3.id,cycle:5)

Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s4.id,cycle:1)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s4.id,cycle:2)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s4.id,cycle:3)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s4.id,cycle:4)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s4.id,cycle:5)

Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s5.id,cycle:1)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s5.id,cycle:2)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s5.id,cycle:3)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s5.id,cycle:4)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s5.id,cycle:5)

Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s6.id,cycle:1)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s6.id,cycle:2)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s6.id,cycle:3)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s6.id,cycle:4)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s6.id,cycle:5)

Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s7.id,cycle:1)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s7.id,cycle:2)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s7.id,cycle:3)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s7.id,cycle:4)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s7.id,cycle:5)

Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s8.id,cycle:1)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s8.id,cycle:2)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s8.id,cycle:3)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s8.id,cycle:4)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s8.id,cycle:5)

Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s9.id,cycle:1)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s9.id,cycle:2)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s9.id,cycle:3)
Assessment.create(participation:false, comment:'Yes',teacher_id:t1.id, student_id:s9.id,cycle:4)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s9.id,cycle:5)

Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s10.id,cycle:1)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s10.id,cycle:2)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s10.id,cycle:3)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s10.id,cycle:4)
Assessment.create(participation:true, comment:'Yes',teacher_id:t1.id, student_id:s10.id,cycle:5)